development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: //pfxfkxpxlhwdoi:d637c6d17b1120ebfc11344bcf8c00012b72a992b949eff18c755c4d4f33069f@ec2-54-225-68-71.compute-1.amazonaws.com:54
  
  
  
  
